require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const path = require('path');
BigInt.prototype.toJSON = function () { return Number(this); };
const routes = require('./src/routes');
const { errorHandler } = require('../../packages/shared/src/middlewares/errorHandler.middleware');
const app = express();
const PORT = process.env.PORT || 3003;
app.set('trust proxy', 1);
const corsOrigins = (process.env.CORS_ORIGIN || '').split(',').map(o => o.trim()).filter(Boolean);
const resolvedCorsOrigins = corsOrigins.length ? corsOrigins : ['http://localhost:5173'];
app.use(helmet());
app.use(cors({ origin: (origin, callback) => { if (!origin) return callback(null, true); if (resolvedCorsOrigins.includes(origin)) return callback(null, true); return callback(new Error('Not allowed by CORS')); }, credentials: true }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
const uploadDir = process.env.UPLOAD_DIR || 'uploads';
app.use('/uploads', express.static(path.join(process.cwd(), uploadDir)));
app.get('/health', (req, res) => res.status(200).json({ status: 'ok', service: 'file-service' }));
app.use('/api', routes);
app.use(errorHandler);
app.listen(PORT, () => console.log(`🚀 File Service on port ${PORT}`));
module.exports = app;