services:
  whisper-api:
    container_name: whisper-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      WHISPER_MODEL: "large-v3"
      WHISPER_DEVICE: "cpu"
      WHISPER_COMPUTE_TYPE: "int8"
    volumes:
      - ./models:/app/models
    ports:
      - "9000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
