/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.10.0 (NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export class BaseApiClient {
    protected transformOptions(options: RequestInit): Promise<RequestInit> {
        // Mock Implementation for now - Inject Token
        const token = localStorage.getItem('access_token');
        if (token) {
            options.headers = {
                ...options.headers,
                'Authorization': 'Bearer ' + token
            };
        }
        return Promise.resolve(options);
    }
}
