services:
  ollama-docker:
    container_name: ollama-ai-musig-elgg 
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11435:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
