// Maps SVG filename → { cellId → keyCode }
// Nested child cells are intentionally omitted — clicks on children bubble up to the parent group.
export const svgKeyMaps: Record<string, Record<string, string>> = {
  'saxophon.svg': {
    'oFCHQTbc_2NbSMXFWgMw-24': 'lh_octave',
    'oFCHQTbc_2NbSMXFWgMw-1':  'lh1',
    'oFCHQTbc_2NbSMXFWgMw-23': 'lh_front_f',
    'oFCHQTbc_2NbSMXFWgMw-2':  'lh2',
    'oFCHQTbc_2NbSMXFWgMw-3':  'lh3',
    'oFCHQTbc_2NbSMXFWgMw-8':  'lh_palm_f',
    'oFCHQTbc_2NbSMXFWgMw-9':  'lh_palm_eb',
    'oFCHQTbc_2NbSMXFWgMw-10': 'lh_palm_d',
    'oFCHQTbc_2NbSMXFWgMw-5':  'rh1',
    'oFCHQTbc_2NbSMXFWgMw-6':  'rh2',
    'oFCHQTbc_2NbSMXFWgMw-7':  'rh3',
    'oFCHQTbc_2NbSMXFWgMw-11': 'lh_pinky_gs',
    'oFCHQTbc_2NbSMXFWgMw-12': 'lh_pinky_low_b',
    'oFCHQTbc_2NbSMXFWgMw-13': 'lh_pinky_low_bb',
    'oFCHQTbc_2NbSMXFWgMw-14': 'rh_pinky_eb',
    'oFCHQTbc_2NbSMXFWgMw-15': 'rh_pinky_low_c',
    'oFCHQTbc_2NbSMXFWgMw-16': 'lh_pinky_low_b',
    'oFCHQTbc_2NbSMXFWgMw-17': 'lh_pinky_low_bb',
    'oFCHQTbc_2NbSMXFWgMw-18': 'rh_pinky_low_cs',
    'oFCHQTbc_2NbSMXFWgMw-19': 'rh_side_bb',
    'oFCHQTbc_2NbSMXFWgMw-20': 'rh_side_c',
    'oFCHQTbc_2NbSMXFWgMw-21': 'rh_side_e',
  },
  'querfloete.svg': {
    'oFCHQTbc_2NbSMXFWgMw-49': 'lh_thumb',
    'oFCHQTbc_2NbSMXFWgMw-50': 'lh1',
    'oFCHQTbc_2NbSMXFWgMw-51': 'lh2',
    'oFCHQTbc_2NbSMXFWgMw-52': 'lh3',
    'oFCHQTbc_2NbSMXFWgMw-53': 'rh1',
    'oFCHQTbc_2NbSMXFWgMw-54': 'rh2',
    'oFCHQTbc_2NbSMXFWgMw-55': 'rh3',
    'oFCHQTbc_2NbSMXFWgMw-56': 'rh_pinky_low_c',
    'oFCHQTbc_2NbSMXFWgMw-57': 'rh_pinky_low_cs',
    'oFCHQTbc_2NbSMXFWgMw-58': 'rh_pinky_eb',
    'oFCHQTbc_2NbSMXFWgMw-59': 'rh_side_c',
    'oFCHQTbc_2NbSMXFWgMw-60': 'rh_pinky_low_a',
    'oFCHQTbc_2NbSMXFWgMw-62': 'lh_pinky_low_b',
    'oFCHQTbc_2NbSMXFWgMw-66': 'rh_side_bb',
    'oFCHQTbc_2NbSMXFWgMw-70': 'rh_side_e',
  },
  'klarinette.svg': {
    'oFCHQTbc_2NbSMXFWgMw-39': 'lh_thumb',
    'oFCHQTbc_2NbSMXFWgMw-40': 'lh_whisper',
    'oFCHQTbc_2NbSMXFWgMw-41': 'lh_octave',
    'oFCHQTbc_2NbSMXFWgMw-27': 'lh1',
    'oFCHQTbc_2NbSMXFWgMw-28': 'lh2',
    'oFCHQTbc_2NbSMXFWgMw-29': 'lh3',
    'oFCHQTbc_2NbSMXFWgMw-30': 'rh1',
    'oFCHQTbc_2NbSMXFWgMw-31': 'rh2',
    'oFCHQTbc_2NbSMXFWgMw-32': 'rh3',
    'oFCHQTbc_2NbSMXFWgMw-35': 'lh_pinky_gs',
    'oFCHQTbc_2NbSMXFWgMw-36': 'lh_pinky_low_b',
    'oFCHQTbc_2NbSMXFWgMw-37': 'rh_pinky_low_cs',
    'oFCHQTbc_2NbSMXFWgMw-38': 'rh_pinky_low_a',
    'oFCHQTbc_2NbSMXFWgMw-25': 'lh_pinky_low_b',
    'oFCHQTbc_2NbSMXFWgMw-26': 'lh_pinky_low_bb',
    'oFCHQTbc_2NbSMXFWgMw-33': 'rh_pinky_eb',
    'oFCHQTbc_2NbSMXFWgMw-34': 'rh_pinky_low_c',
    'oFCHQTbc_2NbSMXFWgMw-45': 'lh_thumb_klappe1',
    'oFCHQTbc_2NbSMXFWgMw-46': 'lh_thumb_klappe2',
    'oFCHQTbc_2NbSMXFWgMw-42': 'rh_side_bb',
    'oFCHQTbc_2NbSMXFWgMw-43': 'rh_side_c',
    'oFCHQTbc_2NbSMXFWgMw-44': 'rh_side_e',
    'oFCHQTbc_2NbSMXFWgMw-47': 'lh_thumb_klappe3',
    'oFCHQTbc_2NbSMXFWgMw-48': 'lh_thumb_klappe4',
  },
  'oboe.svg': {
    'oFCHQTbc_2NbSMXFWgMw-115': 'lh_thumb_klappe1',
    'oFCHQTbc_2NbSMXFWgMw-116': 'lh_thumb_klappe2',
    'oFCHQTbc_2NbSMXFWgMw-117': 'lh1',
    'oFCHQTbc_2NbSMXFWgMw-118': 'lh2',
    'oFCHQTbc_2NbSMXFWgMw-119': 'lh3',
    'oFCHQTbc_2NbSMXFWgMw-120': 'rh1',
    'oFCHQTbc_2NbSMXFWgMw-121': 'rh2',
    'oFCHQTbc_2NbSMXFWgMw-122': 'rh3',
    'oFCHQTbc_2NbSMXFWgMw-123': 'lh_octave',
    'oFCHQTbc_2NbSMXFWgMw-124': 'lh_thumb',
    'oFCHQTbc_2NbSMXFWgMw-125': 'lh_pinky_gs',
    'oFCHQTbc_2NbSMXFWgMw-126': 'lh_pinky_low_b',
    'oFCHQTbc_2NbSMXFWgMw-127': 'lh_pinky_low_bb',
    'oFCHQTbc_2NbSMXFWgMw-130': 'rh_pinky_eb',
    'oFCHQTbc_2NbSMXFWgMw-133': 'rh_pinky_low_c',
    'oFCHQTbc_2NbSMXFWgMw-136': 'rh_pinky_low_cs',
    'oFCHQTbc_2NbSMXFWgMw-139': 'rh_side_bb',
    'oFCHQTbc_2NbSMXFWgMw-142': 'rh_side_c',
    'oFCHQTbc_2NbSMXFWgMw-128': 'rh_side_e',
    'oFCHQTbc_2NbSMXFWgMw-129': 'rh_thumb_c',
    'oFCHQTbc_2NbSMXFWgMw-131': 'rh_thumb_f',
    'oFCHQTbc_2NbSMXFWgMw-132': 'rh_thumb_eb',
    'oFCHQTbc_2NbSMXFWgMw-134': 'rh_thumb_bb',
    'oFCHQTbc_2NbSMXFWgMw-135': 'lh_whisper',
    'oFCHQTbc_2NbSMXFWgMw-137': 'lh_thumb_klappe3',
    'oFCHQTbc_2NbSMXFWgMw-138': 'lh_thumb_klappe4',
    'oFCHQTbc_2NbSMXFWgMw-140': 'rh_pinky_low_a',
    'oFCHQTbc_2NbSMXFWgMw-141': 'lh1',
    'oFCHQTbc_2NbSMXFWgMw-143': 'rh1',
    'oFCHQTbc_2NbSMXFWgMw-144': 'rh2',
  },
  'piccolofloete.svg': {
    'oFCHQTbc_2NbSMXFWgMw-145': 'lh_thumb',
    'oFCHQTbc_2NbSMXFWgMw-146': 'lh1',
    'oFCHQTbc_2NbSMXFWgMw-147': 'lh2',
    'oFCHQTbc_2NbSMXFWgMw-148': 'lh3',
    'oFCHQTbc_2NbSMXFWgMw-149': 'rh1',
    'oFCHQTbc_2NbSMXFWgMw-150': 'rh2',
    'oFCHQTbc_2NbSMXFWgMw-151': 'rh3',
    'oFCHQTbc_2NbSMXFWgMw-152': 'rh_side_bb',
    'oFCHQTbc_2NbSMXFWgMw-153': 'rh_side_c',
    'oFCHQTbc_2NbSMXFWgMw-154': 'rh_side_e',
    'oFCHQTbc_2NbSMXFWgMw-155': 'rh_pinky_eb',
  },
  '3-ventiler.svg': {
    'oFCHQTbc_2NbSMXFWgMw-156': 'v1',
    'oFCHQTbc_2NbSMXFWgMw-157': 'v2',
    'oFCHQTbc_2NbSMXFWgMw-158': 'v3',
  },
  '4-ventiler.svg': {
    'oFCHQTbc_2NbSMXFWgMw-156': 'v1',
    'oFCHQTbc_2NbSMXFWgMw-157': 'v2',
    'oFCHQTbc_2NbSMXFWgMw-158': 'v3',
    'oFCHQTbc_2NbSMXFWgMw-159': 'v4',
  },
};

export const instrumentSvgMap: Record<string, string | null> = {
  flute: 'querfloete.svg',
  piccolo: 'piccolofloete.svg',
  oboe: 'oboe.svg',
  clarinet_bb: 'klarinette.svg',
  bass_clarinet: 'klarinette.svg',
  bassoon: null,
  soprano_sax: 'saxophon.svg',
  alto_sax: 'saxophon.svg',
  tenor_sax: 'saxophon.svg',
  baritone_sax: 'saxophon.svg',
  trumpet_bb: '3-ventiler.svg',
  flugelhorn: '3-ventiler.svg',
  cornet: '3-ventiler.svg',
  eb_horn: '3-ventiler.svg',
  french_horn: '4-ventiler.svg',
  tenor_horn: '3-ventiler.svg',
  baritone_horn: '3-ventiler.svg',
  euphonium: '4-ventiler.svg',
  trombone: null,
  tuba_eb: '4-ventiler.svg',
  tuba_bb: '4-ventiler.svg',
};

// For each SVG, deduplicated list of unique key codes available
export const svgAvailableKeys: Record<string, string[]> = Object.fromEntries(
  Object.entries(svgKeyMaps).map(([svg, map]) => [svg, [...new Set(Object.values(map))]])
);
